<div class="row">

<!-- NEW COL START -->
<div class="col-sm-12">

    <div role="widget" class="jarviswidget" id="wid-id-0">
        
        <header role="heading" style="height:60px;padding:10px">

            <span class="widget-icon"> <i class="fa fa-lg fa-user-md"></i> </span><h2>Noticias</h2>

            <?php if ($_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_SUPERADMIN || $_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_PROFESOR){ ?>

            <div class="pull-right">
                <a class="btn btn-success" href="/admin/foro/edit">
                    <i class="fa fa-plus"></i> Añadir Nuevo artículo
                </a>
            </div>
            <?php } ?>
            <!--<span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>-->

        </header>

        <!-- widget div-->
        <div id="sin_fondo" class="content no-white">

            <!-- widget content -->
            <div class="widget-body no-padding no-white">

                <?php foreach ($this->sources as $source) {?>
                    <div class="new">
                        <h3 class="titulo"><?php echo $source['title'] ?></h3>
                            <div class="excerpt">
                                <?php echo $source['excerpt'] ?>
                            </div>
                            <div style=" text-align: center;" class="imagen_noticia">
                                <img src="<?php echo $this->localUrl()."/".substr($this->escapeHtml($source['mediafile']),7) ?>" alt="" style="max-width: 700px; max-height: 350px;">
                            </div>
                            <div class="contenido">
                                <?php echo $source['comments'] ?>

                            </div>
                        <?php if ($_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_SUPERADMIN || $_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_PROFESOR){ ?>

                            <div class="action pull-right">
                                <a class="delete-action" title="Eliminar" href="#"
                                   data-target-id="<?php echo $source['id'] ?>"
                                   data-action-url="/admin/foro/delete">Eliminar noticia
                                    <span class="<?php echo $this->iconFA('DELETE',false) ?>"></span>
                                </a>
                            </div>
                        <?php } ?>

                    </div>
                <?php } ?>
        </div>
            <!-- end widget content -->

        </div>
        <!-- end widget div -->

    </div>
    <!-- end widget -->

</div>
<!-- END COL -->

</div>

<script type="text/javascript">

   /* $.indexTableSetup = function(){
         $('#index-table').DataTable({
            "oLanguage": {
                "sUrl": "/admin/spanish.json"
            },
            "bFilter": false,
            "bPaginate": false,   
            "bInfo": false,
            "aoColumns": [
                { "bSortable": true },
            ]
        });
    }*/



</script>
