<div class="row">

<!-- NEW COL START -->
<div class="col-sm-12">

    <div role="widget" class="jarviswidget" id="wid-id-0">
        
        <header role="heading" style="height:60px;padding:10px">

            <span class="widget-icon"> <i class="fa fa-lg fa-user-md"></i> </span>
            
            <h2>Log cambios</h2>
            <div class="pull-right">
                <a class="btn btn-success" href="/admin/logger/downloadLogCambios">
                    <i class="fa fa-page"></i>Descargar log
                </a>
            </div>

        </header>

        <!-- widget div-->
        <div role="content">

            <!-- widget content -->
            <div class="widget-body no-padding" id="contenidoLog">
                <input type="hidden" id="puntero" value="<?php echo $this->punteroPosicion ?>">
                <?php echo $this->texto; ?>
            </div>
            <!-- end widget content -->
            <button id="loadMore" onclick="more()" class="btn btn-primary">Ver más</button>
        </div>
        <!-- end widget div -->

    </div>
    <!-- end widget -->

</div>
<!-- END COL -->

</div>

<script type="application/javascript">
    function more(){
        var punteroVal = $('#puntero').val();
        $.ajax({
            type: 'GET',
            dataType: "json",
            url: "/admin/logger/index",
            data: {
                puntero: punteroVal
            },
            success: function (data) {
                if (data.fin){
                    $('#loadMore').hide();
                }else {
                    $('#puntero').val(data.puntero);
                    $('#contenidoLog').append(data.texto);
                }
            }
        });
    }


</script>