<div class="row">

    <!-- NEW COL START -->
    <div class="col-sm-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div role="widget" class="jarviswidget" id="wid-id-0">

            <header role="heading" style="height:60px;padding:10px">

                <span class="widget-icon"> <i class="fa fa-user"></i> </span>

                <h2><strong>Profesor </strong></h2>

                <span class="pull-right">&nbsp;&nbsp;&nbsp;</span>
                <button type="button" class="pull-right btn btn-default" onclick="window.history.back();" style="padding: 6px 12px;height:32px">
                    <i class="fa fa-times"></i> Volver
                </button>

            </header>

            <!-- widget div-->
            <div role="content">
                <!-- widget content -->
                <div class="widget-body no-padding">

                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#detalle">Profesor</a></li>
                    </ul>

                    <div class="tab-content">
                        <div id="detalle" class="tab-pane fade in active">
                            <?php echo $this->partial('backend/admins/_details.phtml', array( 'profesor' => $this->profesor, 'alumnos' => $this->alumnos ));?>
                        </div>

                    </div>

                    <footer style="margin: 10px 15px 0;height:30px">
                    </footer>

                </div>
                <!-- end widget content -->

            </div>
            <!-- end widget div -->

        </div>
        <!-- end widget -->

    </div>
    <!-- END COL -->

</div>