<?php echo $this->headScript()->appendFile('/admin/js/projects.js') ?>
<?php
$this->editUrl   = "/admin/alumnos/edit";
$this->deleteUrl   = "/admin/alumnos/delete";
?>
<div>
    <!-- NEW COL START -->
    <div class="col-sm-12">

        <div role="widget" class="jarviswidget" id="wid-id-0">

            <header role="heading" style="height:60px;padding:10px;" >

                <span class="widget-icon"> <i class="fa fa-folder"></i> </span>

                <h2>Alumnos</h2>

                <div class="pull-right">
                    <a class="btn btn-success" href="<?php echo $this->editUrl ?>">
                        <i class="fa fa-plus"></i> Nuevo Alumno
                    </a>
                </div>

            </header>

            <!-- widget div-->
            <div role="content">




                <table id="alumnos-index-table" class="table table-striped table-bordered dataTable no-footer hover" role="grid" style="width: 100%;" width="100%">
                    <thead>
                    <tr role="row">
                        <th class="index-table-hd" width="35%">Nombre</th>
                        <th class="index-table-hd" width="20%">Correo electrónico</th>
                        <th class="index-table-hd" width="5%">Curso</th>
                        <th class="index-table-hd" width="20%">Tutor</th>
                        <th class="index-table-hd" width="7%">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->alumnosArr as $alumno) {

                        ?>
                        <tr role="row">
                            <td>
                                <a title="Ver" href="/admin/alumnos/show/<?php echo $alumno['id_user']; ?>">
                                <?php echo $this->escapeHtml($alumno['name'])." ".$this->escapeHtml($alumno['lastname']);?>
                                </a>
                            </td>
                            <td><?php echo $this->escapeHtml($alumno['email'])?></td>
                            <td><?php echo $this->escapeHtml($alumno['course'])?></td>
                            <td><?php echo $this->escapeHtml($alumno['tutor']['name'])." ".$this->escapeHtml($alumno['tutor']['lastname']);?></td>


                            <td style="text-align:center">

                                <a class="" title="Editar" href="<?php echo $this->editUrl ?>/<?php echo $alumno['id_user'] ?>">
                                    <span class="<?php echo $this->iconFA('EDIT',false) ?>"></span>
                                </a>
                                |
                                <a title="Ver" href="/admin/alumnos/show/<?php echo $alumno['id_user']; ?>">
                                    <span class="<?php echo $this->iconFA('SHOW',false) ?>"></span>
                                </a>
                                &nbsp;|&nbsp;
                                <a class="delete-action" title="Eliminar" href="#"
                                   data-target-id="<?php echo $alumno['id_user'] ?>"
                                   data-action-url="<?php echo $this->deleteUrl ?>">
                                    <span class="<?php echo $this->iconFA('DELETE',false) ?>"></span>
                                </a>

                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>


            </div>
            <!-- end widget content -->

        </div>
        <!-- end widget div -->

    </div>
    <!-- end widget -->

</div>
</div>
<script type="text/javascript">

    $.indexTableSetup = function(){
        $('#alumnos-index-table').DataTable({
            "oLanguage": {
                "sUrl": "/admin/spanish.json"
            },
            "bFilter": true,
            "bPaginate": true,
            "bInfo": false,
            "aoColumns": [
                { "bSortable": true },
                { "bSortable": true },
                { "bSortable": true },
                { "bSortable": true },
                { "bSortable": true },
            ]
        });
    }

</script>
