<?php echo $this->headScript()->appendFile('/admin/js/projects.js') ?>

<?php
	$this->toggleUrl = "/admin/projects/toggle";
	$this->editUrl   = "/admin/projects/edit";
	$this->deleteUrl = "/admin/projects/del";
	$this->addUrl   = "/admin/projects/add";
?>

<div class="row">

<!-- NEW COL START -->
<div class="col-sm-12">

	<div role="widget" class="jarviswidget" id="wid-id-0">
		
		<header role="heading" style="height:60px;padding:10px;" >

			<span class="widget-icon"> <i class="fa fa-folder"></i> </span>
			
			<h2>Proyectos</h2>

            <?php if ($_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_SUPERADMIN || $_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_PROFESOR){ ?>

            <div class="pull-right">
				<a class="btn btn-success" href="<?php echo $this->editUrl . '?token=' .$this->token ?>">
					<i class="fa fa-plus"></i> Nuevo Proyecto
				</a>
			</div>
            <?php } ?>
		</header>

		<!-- widget div-->
		<div role="content">

                <?php if ($this->busqueda != ''){ ?>
                <div class="widget-body-toolbar">
                    <div class="row search-project-row">
                        <section class="col col-8">
                            <p><?php echo $this->busqueda; ?></p>
                        </section>
                    </div>
                </div>
                <?php } ?>

				<table id="project-index-table" class="table table-striped table-bordered dataTable no-footer hover" role="grid" style="width: 100%;" width="100%">
					<thead>
						<tr role="row">
							<th class="index-table-hd" width="15%">Nombre</th>
							<th class="index-table-hd" width="20%">Alumno</th>
							<th class="index-table-hd" width="5%">Curso</th>
							<th class="index-table-hd" width="11%">Fecha</th>

                            <th class="index-table-hd" width="3%"><?php if($_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_SUPERADMIN || $_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_PROFESOR) { echo 'Acciones'?>
                            <?php } ?></th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->projectsArr as $project) {
						?>
							<tr role="row">
								<td><?php echo $this->escapeHtml($project['titulo'])?></td>
								<td>
                                    <?php if ($_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_SUPERADMIN || $_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_PROFESOR){ ?>

                                    <a href="/admin/alumnos/show/<?php echo $project['id_alumn']; ?>">
                                        <?php } ?>
                                        <?php echo $this->escapeHtml($project['name']." ".$this->escapeHtml($project['lastname']));?>
                                        <?php if ($_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_SUPERADMIN || $_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_PROFESOR){ ?>

                                    </a>
                                    <?php } ?>
                                </td>
								<td><?php echo $this->escapeHtml($project['course'])?></td>
                                <td><?php
                                    $originalDate =$project['created_at'];
                                    $newDate = date("d-m-Y", strtotime($originalDate));
                                    echo $this->escapeHtml($newDate)?></td>


                                <td style="text-align:center">
                                    <?php if($_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_SUPERADMIN || $_SESSION['admin_session']['role'] == \Model\BusinessModel\Usuario::ROL_PROFESOR) {?>

                                    <a class="" title="Editar" href="<?php echo $this->editUrl ?>/<?php echo $project['id_project'] ?>">
		                                <span class="<?php echo $this->iconFA('EDIT',false) ?>"></span>
		                            </a>
                                    &nbsp;|&nbsp;
                                    <a class="delete-action" title="Eliminar" href="#"
                                       data-target-id="<?php echo $project['id_project'] ?>"
                                       data-action-url="<?php echo $this->deleteUrl ?>">
                                        <span class="<?php echo $this->iconFA('DELETE',false) ?>"></span>
                                    </a>
                                    <?php } ?>

                                </td>
							</tr>
						<?php } ?>
					</tbody>
				</table>


			</div>
			<!-- end widget content -->

		</div>
		<!-- end widget div -->

	</div>
	<!-- end widget -->

</div>
<!-- END COL -->

</div>
<script type="text/javascript">

    $.indexTableSetup = function(){
        $('#project-index-table').DataTable({
            "oLanguage": {
                "sUrl": "/admin/spanish.json"
            },
            "bFilter": true,
            "bPaginate": true,
            "bInfo": false,
            "aoColumns": [
                { "bSortable": true },
                { "bSortable": true },
                { "bSortable": true },
                { "bSortable": true },
                { "bSortable": false },
            ]
        });
    }



</script>

