<div class="row">

    <!-- NEW COL START -->
    <div class="col-sm-12">

        <!-- Widget ID (each widget will need unique ID)-->
        <div role="widget" class="jarviswidget" id="wid-id-0">

            <header role="heading" style="height:60px;padding:10px">

                <span class="widget-icon"> <i class="fa fa-gear"></i> </span>

                <h2><strong>Configuración</strong></h2>

                <!--<span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>-->


            </header>
            <!-- widget div-->
            <div role="content">

                <div class="row">
                    <form action="" name="myForm">
                    <label for="color">Color de fondo</label>
                    <input type="radio" name="gender" value="dark"> Dark<br>
                    <input type="radio" name="gender" value="happy"> Happy<br>
                    <input type="radio" name="gender" value="blue"> Blue
                    </form>
                </div>


            </div>
            <!-- end widget div -->


        </div>
        <!-- end widget -->

    </div>
    <!-- END COL -->

</div>

<?php // JS PARA EL EDITOR tinymce ?>
<script type="text/javascript" src="/admin/js/tinymce/tinymce.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {


    });



</script>
