<html lang="ES">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');?>
        <?php echo $this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1'); ?>
        <?php echo $this->headTitle('Administrados de Proyectos')->setAutoEscape(true); ?>

        <link href='http://fonts.googleapis.com/css?family=Noto+Sans:400italic,400,700,700italic' rel='stylesheet' type='text/css'>

<!--        <link href="/assets/stylesheets/all.css" rel="stylesheet" type="text/css" />-->
        <link href="/admin/css/backend-all.css" rel="stylesheet" type="text/css" />

        <link href="/img/favi.png" rel="shortcut icon" type="image/vnd.microsoft.icon">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="/admin/js/libs/html5shiv.min.js" type="text/javascript"></script>
        <script src="/admin/js/libs/respond.js" type="text/javascript"></script>
        <![endif]-->

        <!--[if IE 8]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/2.0.8/es5-shim.min.js"></script>
        <![endif]-->

     </head>

    <body class="hola">

        <header class="header" role="banner">
            <div class="container">
                <div class="row">
                    <div class="col-xs-2">
                    </div>
                    <div class="col-xs-8 text-center">
                        <h4 class="login-title">Gestión de proyectos</h4>
                    </div>
                </div>
            </div>
        </header>

        <div id="main-content" class="main-content login-bg">

                <div class="container self-fadeout">
                    <?php $this->echoFlashMessages( $this->flashMessenger(), "/mpfnimda/login" ); ?>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="login-back">
                                <div class="box box-login" id="box-login">
                                    <h3>Login</h3>
                                    <?php
                                    $this->loginForm->prepare();
                                    echo $this->form()->openTag($this->loginForm);
                                    ?>
                                    <p></p>
                                    <div class="mvm">
                                        Usuario
                                        <?php
                                        $input = $this->loginForm->get('email');
                                        $input->setAttribute('placeholder','Usuario');
                                        echo $this->formRow( $input );
                                        ?>
                                    </div>
                                    <div class="mbs">
                                        Contraseña
                                        <?php
                                        $input = $this->loginForm->get('password');
                                        $input->setAttribute('placeholder','Contraseña');
                                        echo $this->formRow( $input );
                                        echo $this->formElementErrors( $input );
                                        ?>
                                    </div>
                                    <button type="submit" class="mtm button button--full uppercase">Entrar</button>
                                    <?php
                                    echo $this->formRow( $this->loginForm->get('csrf') );
                                    echo $this->form()->closeTag();
                                    ?>
                                    <br>
                                </div><!-- .box -->
                            </div>
                        </div>
                    </div>

                </div>


            <footer class="footer" role="contentinfo">
                <div class="container">
                    <nav role="navigation">
                        <ul>
                            <li>Copyright 2018</li>
                        </ul>
                    </nav>
                </div>
            </footer>


        </div> <!-- main-content -->


    </body>
</html>


