<header class="header">
    <div class="header__toolbar">
        <div class="container">
            <div style="text-align:right;margin:0px">
	            <a href="#" style="opacity: 1;"><strong></strong></a>

            </div>
    	</div>
    </div>
    <div class="container"><img class="header_logo_partner" src="" alt="logo">
        <a class="header__logo" href=""><img src="" alt=""></a>
    </div>
</header><!-- .header -->

