<?php echo $this->doctype(); ?>
<html lang="ES">
    <head>
<!--        <meta charset="UTF-8">-->
        <?php header('Content-type: text/html; charset=utf-8'); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content="IE=edge" http-equiv="X-UA-Compatible">
        <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">

    <title><?php echo '' ?></title>



        <!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<!--        <link href="/assets/stylesheets/dependencies/bootstrap3-5-5.min.css" rel="stylesheet" type="text/css" />-->
        <link href="/assets/stylesheets/dependencies/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="/assets/stylesheets/all.css" rel="stylesheet" type="text/css" />
        <link href="/assets/stylesheets/stylecookies.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/assets/stylesheets/fixes.css" media="screen" rel="stylesheet" type="text/css">


        <link href="/img/favi.png" rel="shortcut icon" type="image/x-icon">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->

    </head>

    <body class="<?php echo $this->bodyClass; ?> background-container">

        <?php echo $this->header;?>

        <?php echo $this->content; ?>
    
        <?php echo $this->footer; ?>

        <script src="/assets/javascripts/dependencies/jquery-1.11.3.min.js" type="text/javascript"></script>
        <script src="/assets/javascripts/dependencies/bootstrap.js" type="text/javascript"></script>
        <script src="/assets/javascripts/dependencies/placeholders.min.js" type="text/javascript"></script>
        <script src="/assets/javascripts/dependencies/selectizeIe8bug.js" type="text/javascript"></script>
        <script src="/assets/javascripts/dependencies/selectize.js" type="text/javascript"></script>
        <script src="/assets/javascripts/dependencies/icheck.min.js" type="text/javascript"></script>
        <script src="/assets/javascripts/dependencies/jquery.validate.min.js"></script>
        <?php if(!preg_match('/(?i)msie [5-8]/',$_SERVER['HTTP_USER_AGENT'])) { ?>
            <script src="/assets/javascripts/custom-file.js"></script>
       <?php } ?>

        <script src="/assets/javascripts/validator-fixes.js"></script>
        <script src="/assets/javascripts/all.js"></script>
        <script src="/assets/javascripts/cookies.min.js" type="text/javascript"></script>
        <script src="/assets/javascripts/cookies.cdata.js" type="text/javascript"></script>

        <?php echo $this->javascript; ?>

    </body>

</html>
